package me.nelonn.quillspace.dto;

public enum RestError {
    // core errors
    INTERNAL_SERVER_ERROR,
    NOT_FOUND,
    NO_PERMISSION,
    UNAUTHORIZED,

    // article errors
    TITLE_IS_EMPTY,
    TITLE_TOO_LONG,
    SUMMARY_TOO_LONG,
    CONTENT_IS_EMPTY,
    CONTENT_TOO_LONG,

    // user errors
    OLD_PASSWORD_IS_EMPTY,
    OLD_PASSWORD_NOT_MATCHES,

    // auth errors
    EMAIL_IS_EMPTY,
    EMAIL_INVALID,
    EMAIL_OCCUPIED,
    EMAIL_NOT_FOUND,
    PASSWORD_IS_EMPTY,
    PASSWORD_TOO_SHORT,
    PASSWORD_TOO_LONG,
    PASSWORD_REQUIRED_ONE_DIGIT,
    PASSWORD_REQUIRED_ONE_LOWERCASE_CHAR,
    PASSWORD_REQUIRED_ONE_UPPERCASE_CHAR,
    PASSWORD_REQUIRED_ONE_SPECIAL_CHAR
}
